/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import static EMPLOYEE.Inquiries.companytf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class Payments extends javax.swing.JFrame {
        Connection con;

    ResultSet rs;
    int q, i, id, deleteItem;
    
PreparedStatement pst;
    public Payments() {
        initComponents();
  
        savebtn.setEnabled(false);
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
   
    clienttf.setEditable(false);
    paymenttf.setEditable(false);
    
            String SUrl,Suser, Spass;
    SUrl = "jdbc:MYSQL://localhost:3306/ja consultancy services";
    Suser = "root";
    Spass = "";
    String query = "SELECT p.*, iap.company_name FROM payment_table p\n" +
"INNER JOIN client_table c ON p.client_id = c.client_id\n" +
"INNER JOIN inquiry_and_proposal iap ON c.IPM_ID = iap.IPM_ID;";
    //String query = "SELECT * FROM payment_table WHERE client_id" + "SELECT company_name FROM inquiry_and_proposal WHERE IPM_ID IN SELECT IPM_ID FROM client_table";
           // + ""(SELECT client_id FROM client_table WHERE IPM_ID = (SELECT IPM_ID FROM inquiry_and_proposal WHERE Company_Name)" ;
    
    try{
             con = DriverManager.getConnection(SUrl,Suser,Spass);
             pst = con.prepareStatement(query);
             rs = pst.executeQuery();
             DefaultTableModel model = (DefaultTableModel)(table.getModel());    
             while(rs.next()){
                 model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
             }
    }catch (Exception ex){
        System.out.println("Error : " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        totalamounttf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clienttf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        searchtf = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        paymenttf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment_ID", "Total_Amount", "Client_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 680, 480);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 660, 80, 30);

        delete.setBackground(new java.awt.Color(255, 204, 204));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(1060, 570, 100, 40);

        edit.setBackground(new java.awt.Color(153, 0, 0));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(730, 570, 100, 40);

        totalamounttf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalamounttf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalamounttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalamounttfActionPerformed(evt);
            }
        });
        jPanel2.add(totalamounttf);
        totalamounttf.setBounds(840, 320, 210, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Amount:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(880, 290, 140, 25);

        clienttf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clienttf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clienttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienttfActionPerformed(evt);
            }
        });
        jPanel2.add(clienttf);
        clienttf.setBounds(840, 440, 210, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Client ID:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(880, 410, 130, 25);

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(950, 570, 100, 40);

        savebtn.setBackground(new java.awt.Color(0, 153, 102));
        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel2.add(savebtn);
        savebtn.setBounds(840, 570, 100, 40);

        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });
        searchtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtfKeyReleased(evt);
            }
        });
        jPanel2.add(searchtf);
        searchtf.setBounds(20, 110, 270, 40);

        search.setBackground(new java.awt.Color(204, 0, 0));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(310, 110, 100, 40);

        paymenttf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymenttf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymenttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttfActionPerformed(evt);
            }
        });
        jPanel2.add(paymenttf);
        paymenttf.setBounds(840, 200, 210, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Payment ID:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(880, 170, 130, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMIN/payments bg.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FileMaintenance().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalamounttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalamounttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalamounttfActionPerformed

    private void clienttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienttfActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed

        if("".equals(totalamounttf.getText())){
        JOptionPane.showMessageDialog(new JFrame(),"Total Amount is Required","Error",JOptionPane.ERROR_MESSAGE);      
    }else{
        try{    
            String SUrl,Suser, Spass;
    SUrl = "jdbc:MYSQL://localhost:3306/ja consultancy services";
    Suser = "root";
    Spass = "";
           con = DriverManager.getConnection(SUrl,Suser,Spass);
   
    pst = con.prepareStatement("UPDATE payment_table SET Total_Amount =?, Client_ID =? where Payment_ID=?");
    pst.setString(1,totalamounttf.getText());
    pst.setString(2,clienttf.getText());
    pst.setString(3,paymenttf.getText());
    
    
    
    int rowsAffected = pst.executeUpdate(); 
    
    if (rowsAffected > 0 ){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRowIndex = table.getSelectedRow();
        
        model.setValueAt(paymenttf.getText(), selectedRowIndex, 0);
        model.setValueAt(totalamounttf.getText(), selectedRowIndex, 1);
        model.setValueAt(clienttf.getText(), selectedRowIndex, 2);

        
       JOptionPane.showMessageDialog(new JFrame(), "Updated Successfully", "Successed!", JOptionPane.OK_CANCEL_OPTION);
       
       paymenttf.setText("");
       totalamounttf.setText("");
       clienttf.setText("");
       
       savebtn.setEnabled(false);

    } else{
        JOptionPane.showMessageDialog(new JFrame(), "Update Failed", "Warning!", JOptionPane.ERROR_MESSAGE);
    }

       
} catch (SQLException ex) {
            Logger.getLogger(adminScheduling.class.getName()).log(Level.SEVERE, null, ex);
       
}
        }
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
          if(table.getSelectedRow() <0){
        JOptionPane.showMessageDialog(null, "Please select an account!");
        
        }else{
          totalamounttf.setEditable(true);
          savebtn.setEnabled(true);
        }                          
                            
                           
                            
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      
        paymenttf.setText("");
        totalamounttf.setText("");
        clienttf.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int id = Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
        try{
               Class.forName("com.mysql.cj.jdbc.Driver");
           
         String url = "jdbc:MYSQL://localhost:3306/ja consultancy services";
         String user = "jaroot";
         String pass = "";
         
         Connection con = DriverManager.getConnection(url,user,pass);
         Statement st = con.createStatement();
         ResultSet res =st.executeQuery("select * from payment_table where Payment_ID ="+id);
                        while(res.next()){
                            paymenttf.setText(res.getString("Payment_ID"));
                            totalamounttf.setText(res.getString("Total_Amount"));
                            clienttf.setText(res.getString("Client_ID"));
                            
                            
                             
                             
                            
                            totalamounttf.setEditable(false);
                        }
                
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableMouseClicked

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtfActionPerformed

    private void searchtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtfKeyReleased
            if(searchtf.getText().equals("")){
                DefaultTableModel model = (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(model);
        table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(""));
            }
    }//GEN-LAST:event_searchtfKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(model);
        table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchtf.getText()));

    }//GEN-LAST:event_searchActionPerformed

    private void paymenttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttfActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRowIndex = table.getSelectedRow();
//    DELETE FROM `inquiry_and_proposal` WHERE 0
try {
    
         int id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        
        int delete = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
        
        if (delete ==JOptionPane.YES_NO_OPTION) {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
         String url = "jdbc:MYSQL://localhost:3306/ja consultancy services";
         String user = "jaroot";
         String pass = "";
         Connection con = DriverManager.getConnection(url,user,pass);
         String sql = "DELETE FROM `payment_table` WHERE Payment_ID=?";
         pst = con.prepareStatement(sql);
         pst.setInt(1,id);
         pst.executeUpdate(); 
        model.removeRow(selectedRowIndex);
        JOptionPane.showMessageDialog(new JFrame(), "Row Deleted Successfully", "Success!", JOptionPane.CANCEL_OPTION);
        
        paymenttf.setText("");
        totalamounttf.setText("");
        clienttf.setText("");
        

    } else {
        JOptionPane.showMessageDialog(new JFrame(), "No Row Selected", "Warning!", JOptionPane.WARNING_MESSAGE);
    }
} catch (Exception ex) {
    Logger.getLogger(InquiriesAdmin.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(new JFrame(), "Deletion Failed", "Error!", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTextField clienttf;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField paymenttf;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTable table;
    private javax.swing.JTextField totalamounttf;
    // End of variables declaration//GEN-END:variables
}
